apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-conf
  labels:
    name: alertmanager-conf
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:25'
      smtp_from: 'alertmanager@gmail.com.org'
      smtp_auth_username: 'kfinalert@gmail.com'
      smtp_auth_password: 'Kf!nal3rt@321'
      smtp_require_tls: false
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: team-1

    receivers:
    - name: team-1
      email_configs:
      - to: 'saiakhil.g@optit.co'
      - to: 'prabhakaran@kaleidofin.com'
      webhook_configs:
      - url: 'http://promteams-service.monitoring.svc.cluster.local:2000/alert_channel'
        send_resolved: true

