apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-volume
  namespace: monitoring
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: custom-aws-sc    
