apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-volume
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: custom-aws-sc    
