apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules-conf
  namespace: monitoring
data:
  kubernetes_alerts.yml: |
    groups:
      - name: kubernetes_alerts
        rules:
        - alert: DeploymentGenerationOff
          expr: kube_deployment_status_observed_generation != kube_deployment_metadata_generation
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Deployment generation does not match expected generation {{ $labels.namespace }}/{{ $labels.deployment }}
            summary: Deployment is outdated
        - alert: DeploymentReplicasNotUpdated
          expr: ((kube_deployment_status_replicas_updated != kube_deployment_spec_replicas)
            or (kube_deployment_status_replicas_available != kube_deployment_spec_replicas))
            unless (kube_deployment_spec_paused == 1)
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Replicas are not updated and available for deployment {{ $labels.namespace }}/{{ $labels.deployment }}
            summary: Deployment replicas are outdated
        - alert: PodzFrequentlyRestarting
          expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
          for: 10m
          labels:
            severity: warning
          annotations:
            description: Pod {{ $labels.namespace }}/{{ $labels.pod }} was restarted {{ $value }} times within the last hour
            summary: Pod is restarting frequently
        - alert: KubeNodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 1h
          labels:
            severity: warning
          annotations:
            description: The Kubelet on {{ $labels.node }} has not checked in with the API,
              or has set itself to NotReady, for more than an hour
            summary: Node status is NotReady
        - alert: KubeManyNodezNotReady
          expr: count(kube_node_status_condition{condition="Ready",status="true"} == 0)
            > 1 and (count(kube_node_status_condition{condition="Ready",status="true"} ==
            0) / count(kube_node_status_condition{condition="Ready",status="true"})) > 0.2
          for: 1m
          labels:
            severity: critical
          annotations:
            description: '{{ $value }}% of Kubernetes nodes are not ready'
        - alert: APIHighLatency
          expr: apiserver_latency_seconds:quantile{quantile="0.99",subresource!="log",verb!~"^(?:WATCH|WATCHLIST|PROXY|CONNECT)$"} > 4
          for: 10m
          labels:
            severity: critical
          annotations:
            description: the API server has a 99th percentile latency of {{ $value }} seconds for {{ $labels.verb }} {{ $labels.resource }}
        - alert: APIServerErrorsHigh
          expr: rate(apiserver_request_count{code=~"^(?:5..)$"}[5m]) / rate(apiserver_request_count[5m]) * 100 > 5
          for: 10m
          labels:
            severity: critical
          annotations:
            description: API server returns errors for {{ $value }}% of requests
        - alert: KubernetesAPIServerDown
          expr: up{job="kubernetes-apiservers"} == 0
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: Apiserver {{ $labels.instance }} is down!
        - alert: KubernetesAPIServersGone
          expr:  absent(up{job="kubernetes-apiservers"})
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: No Kubernetes apiservers are reporting!
            description: Werner Heisenberg says - OMG Where are my apiserverz?
  prometheus_alerts.yml: |
    groups:
    - name: prometheus_alerts
      rules:
      - alert: PrometheusConfigReloadFailed
        expr: prometheus_config_last_reload_successful == 0
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Reloading Prometheus configuration has failed on {{$labels.instance}}.
      - alert: PrometheusNotConnectedToAlertmanagers
        expr: prometheus_notifications_alertmanagers_discovered < 1
        for: 1m
        labels:
          severity: warning
        annotations:
          description: Prometheus {{ $labels.instance}} is not connected to any Alertmanagers
  node_alerts.yml: |
    groups:
    - name: node_alerts
      rules:
      - alert: HighNodeCPU
        expr: instance:node_cpu:avg_rate5m > 80
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: High Node CPU of {{ humanize $value}}% for 1 hour
      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_free_bytes{mountpoint="/"}[1h], 4*3600) < 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Disk on {{ $labels.instance }} will fill in approximately 4 hours.
      - alert: KubernetesServiceDown
        expr: up{job="kubernetes-service-endpoints"} == 0
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: Pod {{ $labels.instance }} is down!
      - alert: KubernetesServicesGone
        expr:  absent(up{job="kubernetes-service-endpoints"})
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: No Kubernetes services are reporting!
          description: Werner Heisenberg says - OMG Where are my servicez?
      - alert: CriticalServiceDown
        expr: node_systemd_unit_state{state="active"} != 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: Service {{ $labels.name }} failed to start.
          description: Service {{ $labels.instance }} failed to (re)start service {{ $labels.name }}.
  node1_alerts.yml: |
    groups:
    - name: node1_alerts
      rules:
      - alert: node_down
        expr: up{job="host-details"} == 0
        for: 1m
        labels:
          severity: "FATAL"
          service: "node"
        annotations:
          description: "Node with hostname {{ $labels.nodename }} and ip {{ $labels.instance }} is down"
          summary: "NODE IS DOWN {{ $labels.nodename }}"
      - alert: node_high_cpu_usage_on_node_WARNING
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="host-details",mode="idle"}[5m])) * 100) >= 70 and (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) < 75
        for: 1m
        labels:
          severity: WARNING
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of CPU. CPU usage is {{ humanize $value}}%.'
          summary: 'HIGH CPU USAGE WARNING ON {{ $labels.instance }}'
      - alert: node_high_cpu_usage_on_node_CRITICAL
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="vm-host-details",mode="idle"}[5m])) * 100) >= 75 and (avg by (instance) (irate(node_cpu_seconds_total{job="vm-node-exporter",mode="idle"}[5m])) * 100) < 80
        for: 1m
        labels:
          severity: CRITICAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of CPU. CPU usage is {{ humanize $value}}%.'
          summary: 'HIGH CPU USAGE WARNING ON {{ $labels.instance }}'
      - alert: node_high_cpu_usage_on_node_FATAL
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job="host-details",mode="idle"}[5m])) * 100) >= 80
        for: 1m
        labels:
          severity: FATAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of CPU. CPU usage is {{ humanize $value}}%.'
          summary: 'HIGH CPU USAGE WARNING ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_node_WARNING
        expr: ((((node_memory_MemTotal_bytes{instance!="prod-server:9110"} - node_memory_MemAvailable_bytes{instance!="prod-server:9110"}) / node_memory_MemTotal_bytes{instance!="prod-server:9110"}) * 100) >= 85 and (((node_memory_MemTotal_bytes{instance!="prod-server:9110"} - node_memory_MemAvailable_bytes{instance!="prod-server:9110"}) / node_memory_MemTotal_bytes{instance!="prod-server:9110"}) * 100) < 90 )
        for: 1m
        labels:
          severity: WARNING
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_node_CRITICAL
        expr: ((((node_memory_MemTotal_bytes{instance!="prod-server:9110"} - node_memory_MemAvailable_bytes{instance!="prod-server:9110"}) / node_memory_MemTotal_bytes{instance!="prod-server:9110"}) * 100) >= 90 and (((node_memory_MemTotal_bytes{instance!="prod-server:9110"} - node_memory_MemAvailable_bytes{instance!="prod-server:9110"}) / node_memory_MemTotal_bytes{instance!="prod-server:9110"}) * 100) < 95 )
        for: 1m
        labels:
          severity: CRITICAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_node_FATAL
        expr: (((node_memory_MemTotal_bytes{instance!="prod-server:9110"} - node_memory_MemAvailable_bytes{instance!="prod-server:9110"}) / node_memory_MemTotal_bytes{instance!="prod-server:9110"}) * 100) >= 95
        for: 1m
        labels:
          severity: FATAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }}is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_prod_server_WARNING
        expr: ((((node_memory_MemTotal_bytes{instance="prod-server:9110"} - node_memory_MemAvailable_bytes{instance="prod-server:9110"}) / node_memory_MemTotal_bytes{instance="prod-server:9110"}) * 100) >= 40 and (((node_memory_MemTotal_bytes{instance="prod-server:9110"} - node_memory_MemAvailable_bytes{instance="prod-server:9110"}) / node_memory_MemTotal_bytes{instance="prod-server:9110"}) * 100) < 45 )
        for: 1m
        labels:
          severity: WARNING
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_prod_server_CRITICAL
        expr: ((((node_memory_MemTotal_bytes{instance="prod-server:9110"} - node_memory_MemAvailable_bytes{instance="prod-server:9110"}) / node_memory_MemTotal_bytes{instance="prod-server:9110"}) * 100) >= 45 and (((node_memory_MemTotal_bytes{instance="prod-server:9110"} - node_memory_MemAvailable_bytes{instance="prod-server:9110"}) / node_memory_MemTotal_bytes{instance="prod-server:9110"}) * 100) < 50 )
        for: 1m
        labels:
          severity: CRITICAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }} is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_high_memory_usage_on_prod_server_FATAL
        expr: (((node_memory_MemTotal_bytes{instance="prod-server:9110"} - node_memory_MemAvailable_bytes{instance="prod-server:9110"}) / node_memory_MemTotal_bytes{instance="prod-server:9110"}) * 100) >= 50
        for: 1m
        labels:
          severity: FATAL
          service: "node"
        annotations:
          description: '{{ $labels.instance }}is using a LOT of MEMORY. MEMORY usage is over {{ humanize $value}}.'
          summary: 'HIGH MEMORY USAGE WARNING TASK ON {{ $labels.instance }}'
      - alert: node_running_out_of_disk_space_WARNING
        expr: (((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes) >= 97 and ((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes) < 98 )
        for: 1m
        labels:
          severity: WARNING
          service: "node"
        annotations:
          description: 'Disk usage is {{ humanize $value }}% on mountpoint: {{$labels.mountpoint}}'
          summary: 'LOW DISK SPACE WARING: NODE {{ $labels.instance }}'
      - alert: node_running_out_of_disk_space_CRITICAL
        expr: (((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes) >= 98 and ((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes) < 99 )
        for: 1m
        labels:
          severity: CRITICAL
          service: "node"
        annotations:
          description: 'Disk usage is {{ humanize $value }}% on mountpoint: {{$labels.mountpoint}}'
          summary: 'LOW DISK SPACE WARING: NODE {{ $labels.instance }}'
      - alert: node_running_out_of_disk_space_FATAL
        expr: ((node_filesystem_size_bytes - node_filesystem_free_bytes) * 100 / node_filesystem_size_bytes) >= 99
        for: 1m
        labels:
          severity: FATAL
          service: "node"
        annotations:
          description: 'Disk usage is {{ humanize $value }}% on mountpoint: {{$labels.mountpoint}}'
          summary: 'LOW DISK SPACE WARING: NODE {{ $labels.instance }}'


          
